env:
  - GO111MODULE=on
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
- main: .
  binary: "gaga"
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
  goarch:
    - amd64
    - arm
    - arm64
archives:
- replacements:
    darwin: 'darwin'
    linux: 'linux'
    windows: 'windows'
    386: "i386"
    amd64: "amd64"
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
