env:
  - GO111MODULE=on
before:
  hooks:
    - go mod download
    - go mod tidy
builds:
- main: .
  binary: "gaga"
  env:
    - CGO_ENABLED=0
  goos:
    - linux
    - darwin
  goarch:
    - amd64
    - arm
    - arm64
archives:
- replacements:
    darwin: 'darwin'
    linux: 'linux'
    amd64: "amd64"
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"