name: Test Scripts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  issues:
    types: [opened]
  
  workflow_dispatch:
    

permissions:
  id-token: write
  contents: write
  pull-requests: write
  issues: write
  

env:
  golang_version: '1.17.8'


jobs:
  golang: 
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '^${{ env.golang_version }}' # The Go version to download (if necessary) and use.
      - run: go version

    # Set up golang in env
      # - name: Setup go
      #   run: |
      #     wget https://dl.google.com/go/go${{ env.golang_version }}.linux-amd64.tar.gz
      #     sudo tar -C /usr/local/ -xzf go${{ env.golang_version }}.linux-amd64.tar.gz
      #     export PATH=$PATH:/usr/local/go/bin
      #     export TEST="Hello workflow!"

      # - name: go version
      #   run: go version
      
      # - name: main.go
      #   run: go run .
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: initial labeling
      #   uses: andymckay/labeler@master
      #   with:
      #     add-labels: "test"