name: 'Test Scripts'

on:
  push:
    branches:
    - main
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
    - main
    paths-ignore:
      - '**.md'
  issues:
    types: [opened]

permissions:   
  id-token: write
  contents: write    # This is required for actions/checkout@v3
  issues: write
  pull-requests: write
  repository-projects: write

env:
  golang_version: '1.16.1'


jobs:
  golang: 
    if: github.event.name == 'pull_request'
    runs-on: ubuntu-latest

    steps: 
    - name: Checkout
      uses: actions/checkout@v3

    # Set up golang in env
    - uses: actions/setup-go@v3
      with:
        go-version: ${{ env.golang_version }} # The Go version to download (if necessary) and use.
    - run: go version

    - name: initial labeling
      uses: andymckay/labeler@master
      with:
        add-labels: "test"
    - uses: actions/github-script@v6
      id: set-result
      with:
        script: return "Hello!"
        result-encoding: string
    - name: Get result
      run: echo "${{steps.set-result.outputs.result}}"