name: Test Scripts

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  issues:
    types: [opened]
  
  workflow_dispatch:
    

env:
  golang_version: '1.16.1'


jobs:
  golang: 
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3

    # Set up golang in env
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.golang_version }} # The Go version to download (if necessary) and use.
      - run: go version

      # - name: initial labeling
      #   uses: andymckay/labeler@master
      #   with:
      #     add-labels: "test"